#!/bin/bash

set -e

pip3 install ansible

PYTHON_USER_BIN=$(python3 -m site --user-base)/bin
export PATH="$PATH:$PYTHON_USER_BIN"

ansible-galaxy install -r requirements.yml

ansible-playbook bootstrap.yml
