#!/bin/bash

function get_cpu_temp() {
  cpu_temp="CPU $(sensors | awk '/Core 0:/ { print $3 }' | tr -d '+.0')"
}

function get_date() {
  date="$(date +"%a, %d %b, %R" | sed 's/\w\+/\u&/g' )"
}

function get_volume() {
  symbol="ON"
  amixer get Master | grep -q off && symbol="OFF"
  volume="$symbol $(amixer get Master | awk '/Mono:/ { print $4 }' | tr -d '[]')"
}

function get_memory() {
  memory="MEM $(free | awk '/Mem.:/ { printf("%3.1f", $3/$2*100) }')%"
}

function get_battery() {
  state=$(acpi | grep -Eo '(Discharging|Charging)')
  level=$(acpi | grep -Eo '[0-9]+%')

  if [ "$state" = "Charging" ]; then
    state_symbol="+"
  else
    state_symbol=""
  fi

  battery="BAT $state_symbol$level"
}

function get_mailcount() {
  count=$(find "$HOME"/Mail/ -type f -ipath "*inbox*new*" | wc -l)
  mailcount="MAIL $count"
}

function get_all() {
  get_cpu_temp
  get_volume
  get_memory
  get_date
  get_battery
  get_mailcount
}

get_all

trap "get_volume" "USR1"
trap "get_mailcount" "USR2"

sec=0

while true
do
  [ $(( sec % 30 )) -eq 0 ] && {
    get_date
    get_cpu_temp
    get_memory
    get_battery
  }

  xsetroot -name "$mailcount | $cpu_temp | $memory | $battery | $volume | $date ⋮"

  sleep 1 & wait && sec=$((sec + 1))
done
