#!/bin/bash

function get_cpu_temp() {
  cpu_temp="CPU $(sensors | awk '/Core 0:/ { print $3 }' | tr -d '+.0')"
}

function get_date() {
  date="$(date +"%a, %d %b, %R" | sed 's/\w\+/\u&/g' )"
}

function get_volume() {
  symbol="ON"
  amixer get Master | grep -q off && symbol="OFF"
  volume="$symbol $(amixer get Master | awk '/Mono:/ { print $4 }' | tr -d '[]')"
}

function get_memory() {
  memory="MEM $(free | awk '/Mem.:/ { printf("%3.1f", $3/$2*100) }')%"
}

function get_battery() {
  state=$(acpi | grep -Eo '(Discharging|Charging)')
  level=$(acpi | grep -Eo '[0-9]+%')

  if [ "$state" = "Charging" ]; then
    state_symbol="+"
  else
    state_symbol=""
  fi

  battery="BAT $state_symbol$level"
}

get_cpu_temp
get_volume
get_memory
get_date
get_battery

trap "get_volume" "RTMIN"

sec=0

while true
do
  get_date
  [ $(( sec % 10 )) -eq 0 ] && get_cpu_temp
  [ $(( sec % 10 )) -eq 0 ] && get_memory
  [ $(( sec % 15 )) -eq 0 ] && get_battery

  xsetroot -name "$cpu_temp | $memory | $battery | $volume | $date ⋮"

  sleep 1 & wait && sec=$((sec + 1))
done
