#!/bin/bash
# this script goes into a file in /usr/share/xsessions
# like this:
# [Desktop Entry]
# Encoding=UTF-8
# Name=Dwm
# Comment=Dynamic window manager
# Exec=/home/phelipe/suckless/dwm/dwm_start
# Icon=dwm
# Type=XSession

nitrogen --restore &
~/suckless/dwm/dwm_statusbar &
redshift &
xautolock -detectsleep -time 15 -locker slock &
numlockx &
compton &
nm-applet &

exec dwm
