#!/bin/bash

function get_volume {
    amixer get Master | grep -o --perl-regex '([0-9]+)(?=%)'
}

function is_mute {
    amixer get Master | grep -o 'off'
}

case $1 in
    up)
        amixer -D pulse set Master on
        amixer -D pulse set Master 5%+
        ;;
    down)
        amixer -D pulse set Master on
        amixer -D pulse set Master 5%-
        ;;
    mute)
        amixer -D pulse set Master 1+ toggle
        ;;
esac

function send_notification {
    if is_mute; then
        dunstify -r 9999 -t 2000 -u normal "Mute"
    else
        dunstify -r 9999 -t 2000 -u normal "Volume: $(get_volume)"
    fi
}

send_notification

kill -SIGRTMIN $(pgrep dwm_statusbar)
