#!/bin/bash

function get_brightness {
  xbacklight -get | awk '{print int($1)}'
}

function send_notification {
  brightness=$(get_brightness)
  notify-send -h string:x-dunst-stack-tag:brightness -t 2000 -u normal -h "int:value:$brightness" "Brightness"
}

case $1 in
  up)
    xbacklight +1
    send_notification
    ;;
  down)
    xbacklight -1
    send_notification
    ;;
esac
