#!/bin/bash

case $1 in
  up)
    amixer -D pulse set Master on
    amixer -D pulse set Master 5%+
    ;;
  down)
    amixer -D pulse set Master on
    amixer -D pulse set Master 5%-
    ;;
  mute)
    amixer -D pulse set Master 1+ toggle
    ;;
esac

pid="$(pgrep dwm-statusbar)"
if [ -n "$pid" ]; then
  kill -SIGUSR1 "$pid"
fi
