#!/bin/bash

function get_volume {
    amixer get Master | grep -o --perl-regex '([0-9]+)(?=%)'
}

function is_mute {
    amixer get Master | grep -o 'off'
}

function send_notification {
    volume=`get_volume`
    if is_mute ; then
        dunstify -r 9999 -t 2000 -u normal "Mute"
    else
        dunstify -r 9999 -t 2000 -u normal "Volume: $volume"
    fi
}

case $1 in
    up)
        amixer -D pulse set Master on > /dev/null
        amixer -D pulse set Master 5%+ > /dev/null
        send_notification
        ;;
    down)
        amixer -D pulse set Master on > /dev/null
        amixer -D pulse set Master 5%- > /dev/null
        send_notification
        ;;
    mute)
        amixer -D pulse set Master 1+ toggle > /dev/null
        send_notification
        ;;
esac
