#!/bin/bash
set -eu

if [[ -z "${1:-}" ]]; then
  echo "Usage: git delete-squashed [branch]"
  exit 1
fi

TARGET_BRANCH=${1}

git checkout -q "$TARGET_BRANCH"
git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do
  mergeBase=$(git merge-base $TARGET_BRANCH $branch) && \
  [[ $(git cherry $TARGET_BRANCH $(git commit-tree $(git rev-parse $branch\^{tree}) -p $mergeBase -m _)) == "-"* ]] && \
  git branch -D $branch
done
