#!/bin/bash
set -euo pipefail

data=$(jq --null-input --arg yaml "$(<"$1")" '{content:$yaml}')
response=$(curl --silent "https://gitlab.com/api/v4/ci/lint" \
--header 'Content-Type: application/json' \
--header "PRIVATE-TOKEN: $(pass show gitlab-token)" \
--data "$data")

echo "$response" | jq .
