#!/bin/bash
set -euo pipefail

urls=$(tmux capture-pane -J -p | grep -oE 'https?://[a-zA-Z0-9./?=_%:-]*' | sort -u)
url=$(echo "$urls" | fzf-tmux -p 50%,50%)

# a URL for easy testing:
# https://google.com

if [[ -n $url ]]; then
  if uname -a | grep -iq microsoft; then
    wslview "$url"
  elif [[ $OSTYPE == "linux"* ]]; then
    xdg-open "$url"
  elif [[ $OSTYPE == "darwin"* ]]; then
    open "$url"
  fi
fi
