#!/usr/bin/env python3
import argparse
import subprocess
import os

ansible_cmd = [
    "ansible-playbook",
    "--ask-become-pass",
    os.path.expanduser("~/dotfiles/bootstrap.yml"),
]

parser = argparse.ArgumentParser(description="Run playbook")
parser.add_argument("tags", nargs="*", help="play tasks tagged with passed values.")
parser.add_argument(
    "--skip",
    action="store_true",
    help="if present, will skip tagged tasks instead.",
)

args, unknown_args = parser.parse_known_args()

skip = args.skip
tags = args.tags

if tags:
    ansible_cmd.extend(["--skip-tags" if skip else "--tags", ",".join(tags)])

ansible_cmd.extend(unknown_args)

subprocess.run(ansible_cmd)
