#!/bin/bash
while read -r line; do
  if echo "$line" | grep -q '^+'; then
    current_time=$(echo "$line" | cut -d' ' -f 2 | sed 's/,/./')
    description=$(echo "$line" | cut -d' ' -f 3-)
    difference="$(echo "$current_time - ${previous_time:-0}" | bc)"
    echo "$difference $description"
    previous_time="$current_time"
  else
    echo "$line"
  fi
done < "$1"
