#!/bin/bash
set -eo pipefail

emulators=$(emulator -list-avds)

if [[ $(echo "$emulators" | wc -l) -eq 1 ]]; then
  emulator=$emulators
else
  emulator=$(emulator -list-avds | fzf --height 40%)
fi

emulator -avd "$emulator" "$@"
