#!/bin/bash

offlineimap_running=$(ps -ef | grep '[o]fflineimap' | wc -l)

if [ $offlineimap_running = "1" ]; then
    killall offlineimap
fi

if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
    echo "oi"
    /usr/bin/offlineimap
fi
