#!/bin/bash
offlineimap_running=$(pgrep '[o]fflineimap' | wc -l)

if [ "$offlineimap_running" = "1" ]; then
    killall offlineimap
fi

if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
    /usr/bin/offlineimap
fi
